name: 'check-if-os-upgradable'
inputs:
  package-tag:
    required: true
outputs:
  result:
    description: 'is-os-upgradable [true, false]'
    value: ${{ steps.result-step.outputs.result }}

runs:
  using: 'composite'
  steps:
    - id: result-step
      shell: bash
      run: |
        docker run --rm -u=root -v $PWD/.ci/check-os-update.sh:/check-os-update.sh:ro --entrypoint /bin/sh ${{ inputs.package-tag }} /check-os-update.sh && true
        echo "::set-output name=result::$?"
