name: build-and-push
inputs:
  package-version:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.package_repo }}:latest
          ${{ env.package_repo }}:${{ inputs.package-version }}