name: 'build and push and auto update docker image'
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '40 * * * *'
env:
  package_repo: ghcr.io/${{ github.repository_owner }}/docker-tinc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - id: get-time
        run: |
          tp=$(date -u +'%Y%m%d_%H%M%S')
          echo "::set-output name=build-time::$tp"
          echo Timestamp: $tp

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: check-if-base-image-updated
        if: ${{ github.event_name == 'schedule' }}
        name: check-if-base-image-updated
        uses: ./.github/actions/check-if-base-image-updated
        with:
          package-tag: ${{ env.package_repo }}:latest

      - id: check-if-os-upgradable
        if: ${{ github.event_name == 'schedule' }}
        name: check-if-os-upgradable
        uses: ./.github/actions/check-if-os-upgradable
        with:
          package-tag: ${{ env.package_repo }}:latest

      - run: |
          echo steps.check-if-base-image-updated.outputs.result = ${{ steps.check-if-base-image-updated.outputs.result }}
          echo steps.check-if-os-upgradable.outputs.result = ${{ steps.check-if-os-upgradable.outputs.result }}

      - if: ${{ steps.check-if-base-image-updated.outcome == 'skipped' || steps.check-if-base-image-updated.outputs.result != '0' || steps.check-if-os-upgradable.outputs.result != '0' }}
        name: Do build and push
        uses: ./.github/actions/build-and-push
        with:
            package-version: ${{ steps.get-time.outputs.build-time }}
